---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

namespace: odpi
name: egeria
version: 0.1.0
readme: README.md
authors:
  - Ljupcho Palashevski <ljupcho.palashevski@ing.com>
  - Christopher Grote <chris@thegrotes.net>
description: Deploy and manage ODPi Egeria OMAG-based applications on native Linux environments
license_file: LICENSE
tags:
  - odpi
  - egeria
dependencies: {}
repository: https://github.com/odpi/egeria-samples
documentation: https://github.com/odpi/egeria-samples/ansible-collection
homepage: https://github.com/odpi/egeria-samples/ansible-collection
issues: https://github.com/odpi/egeria-samples/issues
