---
# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.

- name: "start server instance"
  include: server-instance.yml config={{ item }}
  loop: "{{ admin_omag_server_startup | default([], true) }}"
  when: admin_omag_server_startup is defined
